"""Geo Table

Revision ID: 9797cbc1b865
Revises: e9e068d5a8d7
Create Date: 2024-10-20 10:17:19.257111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9797cbc1b865'
down_revision: Union[str, None] = 'e9e068d5a8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.String(length=50), nullable=False),
    sa.Column('lng', sa.String(length=50), nullable=False),
    sa.Column('addressId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addressId'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo')
    # ### end Alembic commands ###
