"""Address and Companies Relation Removed on User

Revision ID: a264ff6dfbd6
Revises: a4aa4263f14c
Create Date: 2024-10-20 10:43:31.208167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a264ff6dfbd6'
down_revision: Union[str, None] = 'a4aa4263f14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('addresses', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('companies', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'companies')
    op.drop_column('users', 'addresses')
    # ### end Alembic commands ###
