"""Geo Table Problem Fix

Revision ID: a4aa4263f14c
Revises: 9797cbc1b865
Create Date: 2024-10-20 10:41:44.672245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4aa4263f14c'
down_revision: Union[str, None] = '9797cbc1b865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
