"""Address and Companies Relation Removed on User 2

Revision ID: d0a8333cf216
Revises: a264ff6dfbd6
Create Date: 2024-10-20 10:44:12.433808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0a8333cf216'
down_revision: Union[str, None] = 'a264ff6dfbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('company', sa.JSON(), nullable=False))
    op.drop_column('users', 'addresses')
    op.drop_column('users', 'companies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('companies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('addresses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('users', 'company')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
